project:
  type: website
  output-dir: docs

website:
  title: "Dataset Roulette"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data_code.qmd
        text: "Data & Code"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source

